merge w/ hardy factory release

diff --git a/framework/scripts/chroot-scripts/SUCCESS-SCRIPT b/framework/scripts/chroot-scripts/SUCCESS-SCRIPT
--- a/framework/scripts/chroot-scripts/SUCCESS-SCRIPT
+++ b/framework/scripts/chroot-scripts/SUCCESS-SCRIPT
@@ -24,4 +24,48 @@
 #       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 #       MA 02110-1301, USA.
 
-# Success code goes here...
+# BE AWARE THAT THIS SCRIPT IS CALLED FROM OUTSIDE THE CHROOT.
+# The OS is mounted under /target
+
+. /cdrom/scripts/chroot-scripts/fifuncs "target"
+
+set -x
+set -e
+
+IFHALT "(SUCCESS) Clean-Up and Report FI logs ..." > /dev/tty12
+
+rm -rf /etc/mtab
+ln -s /proc/mounts /etc/mtab
+mount -o remount,rw /cdrom
+
+IFHALT "Clean up FI Env..."
+rm -rf /cdrom/scripts/chroot-scripts/os-post/95-set_UTC_TZ.sh
+rm -rf /cdrom/misc/run-tz-fix
+rm -rf /cdrom/misc/tz_offset.py
+rm -rf /cdrom/command.com
+rm -rf /cdrom/autoexec.bat
+rm -rf /cdrom/dellbio.bin
+rm -rf /cdrom/dellrmk.bin
+rm -rf /cdrom/linld.com
+rm -rf /cdrom/cmd.cfg
+
+IFHALT "Clean up FID FAIL & SUCCESS scripts..."
+rm -rf /cdrom/scripts/chroot-scripts/FAIL-SCRIPT
+echo -e "#!/bin/sh\n# Fail code goes here..." > /cdrom/scripts/chroot-scripts/FAIL-SCRIPT
+rm -rf /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT
+echo -e "#!/bin/sh\n# Success code goes here..." > /cdrom/scripts/chroot-scripts/SUCCESS-SCRIPT
+
+IFHALT "Remove Bad line in /etc/fstab"
+sed -i '/\/dev\/sda2/d' /target/etc/fstab
+
+IFHALT "Report the LOG... If applicable"
+chattr -a /target/var/log/installer/chroot.sh.log
+mv -f /target/var/log/installer/chroot.sh.log /tmp/fist.log
+if [ -f /dell/fist/tal ]; then
+	/dell/fist/tal PutFiles /tmp/fist.log
+	dpkg -r fist
+	rm -rf /dell
+	rm -rf /cdrom/debs/fist
+fi
+
+IFHALT "SUCCESS-SCRIPT is Done!"
